# Generated by Django 3.2.6 on 2021-10-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_campo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='contador',
            field=models.IntegerField(default=1, verbose_name='contador'),
            preserve_default=False,
        ),
    ]
