# Generated by Django 3.2.6 on 2021-10-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_atividade_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
