# Generated by Django 3.2.6 on 2021-10-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_campo_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='contador',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='contador'),
        ),
    ]
