# Generated by Django 3.2.6 on 2021-10-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_campo_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdf/'),
        ),
    ]
