# Generated by Django 3.2.6 on 2021-10-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_atividade_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdf/'),
        ),
    ]
